version: ''

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - DISCOVERY_TYPE=single-node
    healthcheck:
     test: "CMD-SHELL curl -X GET http://localhost:9200/_cluster/health?pretty=true"
     interval: 30s
     timeout: 10s
     retries: 5
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.1
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana-data:/var/lib/kibana/data

networks:
  elk_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24


